// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package gpio_ctrl_bank_csr_pkg;

    localparam GPIO_CTRL_BANK_CSR_DATA_WIDTH = 32;
    localparam GPIO_CTRL_BANK_CSR_MIN_ADDR_WIDTH = 4;
    localparam GPIO_CTRL_BANK_CSR_SIZE = 'h10;

    typedef struct {
        logic [31:0] next;
    } gpio_ctrl_bank_csr__input_data_r__idata__in_t;

    typedef struct {
        gpio_ctrl_bank_csr__input_data_r__idata__in_t idata;
    } gpio_ctrl_bank_csr__input_data_r__in_t;

    typedef struct {
        gpio_ctrl_bank_csr__input_data_r__in_t input_data;
    } gpio_ctrl_bank_csr__in_t;

    typedef struct {
        logic [31:0] value;
    } gpio_ctrl_bank_csr__output_enable_r__oenable__out_t;

    typedef struct {
        gpio_ctrl_bank_csr__output_enable_r__oenable__out_t oenable;
    } gpio_ctrl_bank_csr__output_enable_r__out_t;

    typedef struct {
        logic [31:0] value;
    } gpio_ctrl_bank_csr__output_data_r__odata__out_t;

    typedef struct {
        gpio_ctrl_bank_csr__output_data_r__odata__out_t odata;
    } gpio_ctrl_bank_csr__output_data_r__out_t;

    typedef struct {
        logic [31:0] value;
    } gpio_ctrl_bank_csr__level_change_intr_enable_r__intr_enable__out_t;

    typedef struct {
        gpio_ctrl_bank_csr__level_change_intr_enable_r__intr_enable__out_t intr_enable;
    } gpio_ctrl_bank_csr__level_change_intr_enable_r__out_t;

    typedef struct {
        gpio_ctrl_bank_csr__output_enable_r__out_t output_enable;
        gpio_ctrl_bank_csr__output_data_r__out_t output_data;
        gpio_ctrl_bank_csr__level_change_intr_enable_r__out_t intr_enable;
    } gpio_ctrl_bank_csr__out_t;
endpackage
